[package]
name = "chip-8_rust"
version = "0.1.0"
authors = ["Matthew Berry <me@mattrb.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.7"
